# This is a basic workflow to help you get started with Actions

name: Github Actions

# git push --tags 执行时候进行编译
on: [push, pull_request]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with: 
            distribution: 'zulu'
            java-version: "17"
            token: ${{secrets.GITHUB_TOKEN}}

      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
            flutter-version: 3.10.0-16.0.pre.26
            channel: master
      
      - name: Decode keystore
        run: |
          echo $ENCODED_KEYSTORE | base64 -di > android/app/keystore.jks
        env:
          ENCODED_KEYSTORE: ${{ secrets.KEYSTORE }}

      - run: flutter pub get
      # 打包apk
      - name: Collect Apks
        run: flutter build apk --release --split-per-abi
      - run: |
          mv build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk build/app/outputs/flutter-apk/bili_you_test_android-armeabi-v7a.apk
          mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk build/app/outputs/flutter-apk/bili_you_test_android-arm64-v8a.apk
          mv build/app/outputs/flutter-apk/app-x86_64-release.apk build/app/outputs/flutter-apk/bili_you_test_android-x86_64.apk
      - uses: actions/upload-artifact@v1
        with:
          name: bili_you_test_android-armeabi-v7a
          path: build/app/outputs/flutter-apk/bili_you_test_android-armeabi-v7a.apk
          
      - uses: actions/upload-artifact@v1
        with:
          name: bili_you_test_android-arm64-v8a
          path: build/app/outputs/flutter-apk/bili_you_test_android-arm64-v8a.apk
          
      - uses: actions/upload-artifact@v1
        with:
          name: bili_you_test_android-x86_64
          path: build/app/outputs/flutter-apk/bili_you_test_android-x86_64.apk
